[package]
name = "ff6"
version = "0.1.0"
authors = ["Erik Gilling <konkers@konkers.net>"]

[dependencies]
serde = "1.0.80"
serde_derive = "1.0.80"
simple-error = "0.1.12"
toml = "0.4"

[dependencies.nom]
version = "4.1.1"
features = ["verbose-errors"]